[theme]
primaryColor = "#e6194b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f9fa"
textColor = "#1e293b"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
